DeVillage V0.2/devillage/core/urls.py
from django.urls import path 
from . import views
app_name = 'core'

urlpatterns = [
    #path('',views.Index, name= "index")
]

DeVillage V0.2/devillage/devillage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('posts.urls')),
]

DeVillage V0.2/devillage/posts/urls.py
from django.urls import path
from . import views
app_name = 'post_app'

urlpatterns = [
    path('',views.Post,name='post'),
    path('<int:pk>/',views.details, name = 'details'),
    path('about/', views.about, name = 'about'),
    path('contact/', views.contact, name = 'contact'),
]

DeVillage V0.2/devillage/core/models.py
from django.db import models

# Create your models here.

DeVillage V0.2/devillage/posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name
    
class Posts(models.Model):
    category = models.ForeignKey(Category, related_name= 'posts',default='', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    post = models.TextField(max_length= 100000, blank = False)
    created_by = models.ForeignKey(User, related_name= 'posts' ,default= User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title
    

DeVillage V0.2/devillage/core/views.py
from django.shortcuts import render
from posts.models import Posts

#def Index(request):
#    post = Posts.objects.all()
#
#    return render(request, 'templates/index.html',{
#        'post':post
#    })

DeVillage V0.2/devillage/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Posts


def Post(request):
    posts = Posts.objects.all()
    return render(request, 'templates/index.html',{
        'posts':posts
    })

def details(request, pk):
    post_detail = get_object_or_404(Posts,pk= pk)
    return render(request, 'templates/detail.html',
                  {'detail' : post_detail})

def about(request):
    return render(request, 'templates/about.html')

def contact(request):
    return render(request, 'templates/contact.html')

DeVillage V0.2/devillage/templates/about.html
{%extends 'templates/base.html'%}
{%block title%}About {%endblock%}

{%block content%}
    <h1 style="margin-top: 20px; margin-left: 10px;">
        About
    </h1>
    <div style="margin: 30px;">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus quasi, iure quas reprehenderit neque quisquam, obcaecati commodi, 
            cumque ut voluptatum doloremque. Quia, eveniet repudiandae? Quod ab quasi cum doloremque dolore sapiente quam, possimus accusamus eius delectus 
            illum odit in corporis recusandae fugiat unde consequatur saepe veritatis 
            rerum doloribus quis nulla ducimus? Quo dicta architecto dignissimos?</p><br>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod possimus similique blanditiis dignissimos perspiciatis dolores 
            illum nemo ullam quo! Rerum error, minus, voluptas, earum culpa officiis omnis reiciendis aliquam possimus at cum placeat cumque? 
            Dolorem animi dolore quod excepturi molestiae corrupti et enim pariatur! Aspernatur, modi ipsum ut repudiandae laudantium cum numquam, 
            delectus praesentium provident suscipit, quis quisquam nobis iusto eligendi quaerat. 
            Eaque molestiae pariatur est totam ab! Iure, ipsam.
            <br></p>
        <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Placeat velit explicabo, architecto quaerat illo numquam consequuntur, 
            dicta alias eaque praesentium deleniti quisquam dolorem eius dolorum ipsum. Labore sequi, officiis nesciunt exercitationem ipsam recusandae, 
            veritatis cum eius deserunt corporis dolor voluptatibus fuga ducimus magnam animi aliquam? Cumque nihil laudantium pariatur dignissimos nisi natus eum 
            deserunt tempora exercitationem! Blanditiis assumenda placeat repellendus veritatis, ducimus consectetur ratione vero, quod sed aperiam necessitatibus quae cum 
            tenetur ad repellat, totam sapiente ut. Aspernatur, eius ipsa voluptatibus exercitationem vero quo ducimus nostrum! 
            Facere, sed. Nemo eum quasi dicta est ab quo odio dolorum distinctio tempora, sed labore ipsum recusandae amet corrupti 
            blanditiis omnis nulla quas rerum quae et soluta ut eveniet cumque impedit! Eveniet totam ipsam repellat amet minima quae sint sunt, 
            exercitationem voluptate aut ut incidunt doloremque officia obcaecati veritatis ullam rerum itaque tenetur fugit molestiae quis dolore! 
            Sapiente, totam? Commodi aliquid voluptate maxime distinctio!
        </p>
    </div>
{%endblock%}

DeVillage V0.2/devillage/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <title>{%block title%} {%endblock%} | Devillage 2</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">DeVillage</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'post_app:about'%}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'post_app:contact' %}">Contact Us</a>
          </li>
          
         <!--- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
             More
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Link</a>
          </li>--->
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
     
    <div>
    {%block content%}

    {%endblock%}
    </div>
   
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</html>

DeVillage V0.2/devillage/templates/contact.html
{%extends 'templates/base.html'%}
{%block title%}Contact{%endblock%}

{%block content%}
    <h1 style="margin-top: 20px; margin-left: 10px;">Contact</h1>
{%endblock%}

DeVillage V0.2/devillage/templates/detail.html
{%extends 'templates/base.html'%}

{%block title%}{{detail.title}} |{%endblock%}


{%block content%}
<div style="padding: 30px;">
    <h1>{{detail.title}}</h1>
   
    <p>{{detail.post}}</p><br>
    <p><i>Author - {{detail.created_by}} / {{detail.category}} </i></p>
</div>
{%endblock%}

DeVillage V0.2/devillage/templates/index.html
{%extends 'templates/base.html'%}
{%block title%}Home {%endblock%}

{%block content%}
<h1 style="margin-left: 10px;">Posts</h1>
    {%for post in posts%}
    <div style="margin: 30px;">    
        <a style="text-decoration: none; color: black;" href="{%url 'post_app:details' post.id%}"><h3>{{post.title}}</h3></a>
        <p>{{post.post}}</p>
        <small><i>Author - {{post.created_by}} / {{post.category}}</i></small>
    </div>
    {%endfor%}
{%endblock%}